/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces 
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29571commondata

type ArpRm struct {
	PriorityLevel int32 `json:"priorityLevel" xml:"priorityLevel"`
	PreemptCap PreemptionCapability `json:"preemptCap" xml:"preemptCap"`
	PreemptVuln PreemptionVulnerability `json:"preemptVuln" xml:"preemptVuln"`
}
