/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces 
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29571commondata
import (
	"time"
)

type QosFlowUsageReport struct {
	Qfi int32 `json:"qfi" xml:"qfi"`
	StartTimeStamp time.Time `json:"startTimeStamp" xml:"startTimeStamp"`
	EndTimeStamp time.Time `json:"endTimeStamp" xml:"endTimeStamp"`
	DownlinkVolume int64 `json:"downlinkVolume" xml:"downlinkVolume"`
	UplinkVolume int64 `json:"uplinkVolume" xml:"uplinkVolume"`
}
