/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces 
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29571commondata

type Dynamic5Qi struct {
	ResourceType QosResourceType `json:"resourceType" xml:"resourceType"`
	PriorityLevel int32 `json:"priorityLevel" xml:"priorityLevel"`
	PacketDelayBudget int32 `json:"packetDelayBudget" xml:"packetDelayBudget"`
	PacketErrRate string `json:"packetErrRate" xml:"packetErrRate"`
	AverWindow int32 `json:"averWindow,omitempty" xml:"averWindow"`
	MaxDataBurstVol int32 `json:"maxDataBurstVol,omitempty" xml:"maxDataBurstVol"`
}
