/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces 
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29571commondata

type OdbData struct {
	RoamingOdb RoamingOdb `json:"roamingOdb,omitempty" xml:"roamingOdb"`
	OdbPacketServices OdbPacketServices `json:"odbPacketServices,omitempty" xml:"odbPacketServices"`
}
