/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces 
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29571commondata

type SubscribedDefaultQos struct {
	Var5qi int32 `json:"5qi" xml:"5qi"`
	Arp Arp `json:"arp" xml:"arp"`
	PriorityLevel int32 `json:"priorityLevel,omitempty" xml:"priorityLevel"`
}
