/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces 
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29571commondata
import (
	"time"
)

type EutraLocation struct {
	Tai Tai `json:"tai" xml:"tai"`
	Ecgi Ecgi `json:"ecgi" xml:"ecgi"`
	AgeOfLocationInformation int32 `json:"ageOfLocationInformation,omitempty" xml:"ageOfLocationInformation"`
	UeLocationTimestamp time.Time `json:"ueLocationTimestamp,omitempty" xml:"ueLocationTimestamp"`
	GeographicalInformation string `json:"geographicalInformation,omitempty" xml:"geographicalInformation"`
	GeodeticInformation string `json:"geodeticInformation,omitempty" xml:"geodeticInformation"`
	GlobalNgenbId GlobalRanNodeId `json:"globalNgenbId,omitempty" xml:"globalNgenbId"`
}
