/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces 
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29571commondata

type ChangeItem struct {
	Op ChangeType `json:"op" xml:"op"`
	Path string `json:"path" xml:"path"`
	From string `json:"from,omitempty" xml:"from"`
	OrigValue map[string]interface{} `json:"origValue,omitempty" xml:"origValue"`
	NewValue map[string]interface{} `json:"newValue,omitempty" xml:"newValue"`
}
