/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces 
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29571commondata

type PresenceInfo struct {
	PraId string `json:"praId,omitempty" xml:"praId"`
	PresenceState PresenceState `json:"presenceState,omitempty" xml:"presenceState"`
	TrackingAreaList []Tai `json:"trackingAreaList,omitempty" xml:"trackingAreaList"`
	EcgiList []Ecgi `json:"ecgiList,omitempty" xml:"ecgiList"`
	NcgiList []Ncgi `json:"ncgiList,omitempty" xml:"ncgiList"`
	GlobalRanNodeIdList []GlobalRanNodeId `json:"globalRanNodeIdList,omitempty" xml:"globalRanNodeIdList"`
}
