/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces 
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29571commondata

type NonDynamic5Qi struct {
	PriorityLevel int32 `json:"priorityLevel,omitempty" xml:"priorityLevel"`
	AverWindow int32 `json:"averWindow,omitempty" xml:"averWindow"`
	MaxDataBurstVol int32 `json:"maxDataBurstVol,omitempty" xml:"maxDataBurstVol"`
}
