/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces 
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29571commondata

type TraceData struct {
	TraceRef string `json:"traceRef" xml:"traceRef"`
	TraceDepth TraceDepth `json:"traceDepth" xml:"traceDepth"`
	NeTypeList string `json:"neTypeList" xml:"neTypeList"`
	EventList string `json:"eventList" xml:"eventList"`
	CollectionEntityIpv4Addr string `json:"collectionEntityIpv4Addr,omitempty" xml:"collectionEntityIpv4Addr"`
	CollectionEntityIpv6Addr string `json:"collectionEntityIpv6Addr,omitempty" xml:"collectionEntityIpv6Addr"`
	InterfaceList string `json:"interfaceList,omitempty" xml:"interfaceList"`
}
