/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces 
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29571commondata

type RouteInformation struct {
	Ipv4Addr string `json:"ipv4Addr,omitempty" xml:"ipv4Addr"`
	Ipv6Addr string `json:"ipv6Addr,omitempty" xml:"ipv6Addr"`
	PortNumber int32 `json:"portNumber" xml:"portNumber"`
}
