/*
 * Common Data Types
 *
 * Common Data Types
 *
 * API version: 1.R15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

type NrLocation struct {
	Tai Tai `json:"tai" xml:"tai"`
	Ncgi Ncgi `json:"ncgi" xml:"ncgi"`
}
