/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type SmContextCreateBody struct {
	JsonData SmContextCreateData `json:"jsonData,omitempty"`

	//BinaryDataN1SmMessage **os.File `json:"binaryDataN1SmMessage,omitempty"`
	BinaryDataN1SmMessage []byte `json:"binaryDataN1SmMessage,omitempty"`
}