/*
 * Common Data Types
 *
 * Common Data Types
 *
 * API version: 1.R15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

type Arp struct {
	PriorityLevel int32 `json:"priorityLevel" xml:"priorityLevel"`
	PreemptCap PreemptionCapability `json:"preemptCap" xml:"preemptCap"`
	PreemptVuln PreemptionVulnerability `json:"preemptVuln" xml:"preemptVuln"`
}
