/*
 * Common Data Types
 *
 * Common Data Types
 *
 * API version: 1.R15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

type InvalidParam struct {
	Param string `json:"param" xml:"param"`
	Reason string `json:"reason,omitempty" xml:"reason"`
}
