/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type OdbData struct {

	RoamingOdb *RoamingOdb `json:"roamingOdb,omitempty"`

	OdbPacketServices *OdbPacketServices `json:"odbPacketServices,omitempty"`
}
