/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type InlineResponse200 struct {

	// List of the URI of NF instances. It has two members whose names are item and self. The item one contains an array of URIs.
	Links map[string]LinksValueSchema `json:"_links,omitempty"`
}
