/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type UpSecurity struct {

	UpIntegr *UpIntegrity `json:"upIntegr"`

	UpConfid *UpConfidentiality `json:"upConfid"`
}
