/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type UserLocation struct {

	EutraLocation *EutraLocation `json:"eutraLocation,omitempty"`

	NrLocation *NrLocation `json:"nrLocation,omitempty"`

	N3gaLocation *N3gaLocation `json:"n3gaLocation,omitempty"`
}
