/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type NgApCause struct {

	Group int32 `json:"group"`

	Value int32 `json:"value"`
}
