/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type ArpRm struct {

	PriorityLevel int32 `json:"priorityLevel"`

	PreemptCap *PreemptionCapability `json:"preemptCap"`

	PreemptVuln *PreemptionVulnerability `json:"preemptVuln"`
}
