/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type AmbrRm struct {

	Uplink string `json:"uplink"`

	Downlink string `json:"downlink"`
}
