/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type Ipv4AddressRange struct {

	Start string `json:"start,omitempty"`

	End string `json:"end,omitempty"`
}
