/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type ChfServiceInfo struct {

	PrimaryChfServiceInstance string `json:"primaryChfServiceInstance,omitempty"`

	SecondaryChfServiceInstance string `json:"secondaryChfServiceInstance,omitempty"`
}
