/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type InterfaceUpfInfoItem struct {

	InterfaceType *UpInterfaceType `json:"interfaceType"`

	Ipv4EndpointAddresses []string `json:"ipv4EndpointAddresses,omitempty"`

	Ipv6EndpointAddresses []string `json:"ipv6EndpointAddresses,omitempty"`

	EndpointFqdn string `json:"endpointFqdn,omitempty"`

	NetworkInstance string `json:"networkInstance,omitempty"`
}
