/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type NotifyItem struct {

	ResourceId string `json:"resourceId,omitempty"`

	Changes []ChangeItem `json:"changes,omitempty"`
}
