/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type NotifCondition struct {

	MonitoredAttributes []string `json:"monitoredAttributes,omitempty"`

	UnmonitoredAttributes []string `json:"unmonitoredAttributes,omitempty"`
}
