/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type Atom struct {

	Attr string `json:"attr"`

	Value *map[string]interface{} `json:"value"`

	Negative bool `json:"negative,omitempty"`
}
