/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type ComplexQuery struct {

	CnfUnits []CnfUnit `json:"cnfUnits"`

	DnfUnits []DnfUnit `json:"dnfUnits"`
}
