/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type ChangeItem struct {

	Op *ChangeType `json:"op"`

	Path string `json:"path"`

	From string `json:"from,omitempty"`

	OrigValue *map[string]interface{} `json:"origValue,omitempty"`

	NewValue *map[string]interface{} `json:"newValue,omitempty"`
}
