/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type PatchItem struct {

	Op *PatchOperation `json:"op"`

	Path string `json:"path"`

	From string `json:"from,omitempty"`

	Value *map[string]interface{} `json:"value,omitempty"`
}
