/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type NetworkId struct {

	Mnc string `json:"mnc,omitempty"`

	Mcc string `json:"mcc,omitempty"`
}
