/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type DefaultNotificationSubscription struct {

	NotificationType *NotificationType `json:"notificationType"`

	CallbackUri string `json:"callbackUri"`

	N1MessageClass *N1MessageClass `json:"n1MessageClass,omitempty"`

	N2InformationClass *N2InformationClass `json:"n2InformationClass,omitempty"`
}
