/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type GuamiRm struct {

	PlmnId *PlmnId `json:"plmnId"`

	AmfId string `json:"amfId"`
}
