/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

type InvalidParam2 struct {

	Param string `json:"param"`

	Reason string `json:"reason,omitempty"`
}
