/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package svcmngserver

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		"GET",
		"/nnrf-nfm/v1/",
		Index,
	},

	{
		"DeregisterNFInstance",
		strings.ToUpper("Delete"),
		"/nnrf-nfm/v1/nf-instances/{nfInstanceID}",
		DeregisterNFInstance,
	},

	{
		"GetNFInstance",
		strings.ToUpper("Get"),
		"/nnrf-nfm/v1/nf-instances/{nfInstanceID}",
		GetNFInstance,
	},

	{
		"RegisterNFInstance",
		strings.ToUpper("Put"),
		"/nnrf-nfm/v1/nf-instances/{nfInstanceID}",
		RegisterNFInstance,
	},

	{
		"UpdateNFInstance",
		strings.ToUpper("Patch"),
		"/nnrf-nfm/v1/nf-instances/{nfInstanceID}",
		UpdateNFInstance,
	},

	{
		"GetNFInstances",
		strings.ToUpper("Get"),
		"/nnrf-nfm/v1/nf-instances",
		GetNFInstances,
	},

	{
		"RemoveSubscription",
		strings.ToUpper("Delete"),
		"/nnrf-nfm/v1/subscriptions/{subscriptionID}",
		RemoveSubscription,
	},

	{
		"UpdateSubscription",
		strings.ToUpper("Patch"),
		"/nnrf-nfm/v1/subscriptions/{subscriptionID}",
		UpdateSubscription,
	},

	{
		"CreateSubscription",
		strings.ToUpper("Post"),
		"/nnrf-nfm/v1/subscriptions",
		CreateSubscription,
	},
}
