/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type VsmfUpdatedData struct {

	QosFlowsAddModList []QosFlowItem `json:"qosFlowsAddModList,omitempty"`

	QosFlowsRelList []QosFlowItem `json:"qosFlowsRelList,omitempty"`

	QosFlowsFailedtoAddModList []QosFlowItem `json:"qosFlowsFailedtoAddModList,omitempty"`

	QosFlowsFailedtoRelList []QosFlowItem `json:"qosFlowsFailedtoRelList,omitempty"`

	N1SmInfoFromUe *map[string]interface{} `json:"n1SmInfoFromUe,omitempty"`

	UnknownN1SmInfo *map[string]interface{} `json:"unknownN1SmInfo,omitempty"`

	UeLocation *map[string]interface{} `json:"ueLocation,omitempty"`

	UeTimeZone *map[string]interface{} `json:"ueTimeZone,omitempty"`

	AddUeLocation *map[string]interface{} `json:"addUeLocation,omitempty"`

	AssignedEbiList []EbiArpMapping `json:"assignedEbiList,omitempty"`

	FailedToAssignEbiList []int32 `json:"failedToAssignEbiList,omitempty"`

	ReleasedEbiList []int32 `json:"releasedEbiList,omitempty"`

	SecondaryRatUsageReport []map[string]interface{} `json:"secondaryRatUsageReport,omitempty"`

	SecondaryRatUsageInfo []map[string]interface{} `json:"secondaryRatUsageInfo,omitempty"`
}
