/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type SmContextCreateError struct {

	Error *map[string]interface{} `json:"error"`

	N1SmMsg *map[string]interface{} `json:"n1SmMsg,omitempty"`

	RecoveryTime *map[string]interface{} `json:"recoveryTime,omitempty"`
}
