/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type TunnelInfo struct {

	Ipv4Addr *map[string]interface{} `json:"ipv4Addr,omitempty"`

	Ipv6Addr *map[string]interface{} `json:"ipv6Addr,omitempty"`

	GtpTeid string `json:"gtpTeid"`
}
