/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"os"
)

type InlineObject struct {

	JsonData *SmContextCreateData `json:"jsonData,omitempty"`

	BinaryDataN1SmMessage **os.File `json:"binaryDataN1SmMessage,omitempty"`

	BinaryDataN2SmInformation **os.File `json:"binaryDataN2SmInformation,omitempty"`
}
