/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// EpsInterworkingIndication - Possible values are - NONE - WITH_N26 - WITHOUT_N26 - IWK_NON_3GPP 
type EpsInterworkingIndication struct {
}
