/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type EpsBearerInfo struct {

	Ebi int32 `json:"ebi"`

	PgwS8uFteid *map[string]interface{} `json:"pgwS8uFteid"`

	BearerLevelQoS *map[string]interface{} `json:"bearerLevelQoS"`
}
