/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// MaReleaseIndication - Possible values are   - REL_MAPDU_OVER_3GPP   - REL_MAPDU_OVER_N3GPP 
type MaReleaseIndication struct {
}
