/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type QosFlowAddModifyRequestItem struct {

	Qfi *map[string]interface{} `json:"qfi"`

	Ebi int32 `json:"ebi,omitempty"`

	QosRules *map[string]interface{} `json:"qosRules,omitempty"`

	QosFlowDescription *map[string]interface{} `json:"qosFlowDescription,omitempty"`

	QosFlowProfile *QosFlowProfile `json:"qosFlowProfile,omitempty"`
}
