/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type GbrQosFlowInformation struct {

	MaxFbrDl *map[string]interface{} `json:"maxFbrDl"`

	MaxFbrUl *map[string]interface{} `json:"maxFbrUl"`

	GuaFbrDl *map[string]interface{} `json:"guaFbrDl"`

	GuaFbrUl *map[string]interface{} `json:"guaFbrUl"`

	NotifControl *map[string]interface{} `json:"notifControl,omitempty"`

	MaxPacketLossRateDl *map[string]interface{} `json:"maxPacketLossRateDl,omitempty"`

	MaxPacketLossRateUl *map[string]interface{} `json:"maxPacketLossRateUl,omitempty"`
}
