/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type ReleaseData struct {

	Cause *Cause `json:"cause,omitempty"`

	NgApCause *map[string]interface{} `json:"ngApCause,omitempty"`

	Var5gMmCauseValue *map[string]interface{} `json:"5gMmCauseValue,omitempty"`

	UeLocation *map[string]interface{} `json:"ueLocation,omitempty"`

	UeTimeZone *map[string]interface{} `json:"ueTimeZone,omitempty"`

	AddUeLocation *map[string]interface{} `json:"addUeLocation,omitempty"`

	SecondaryRatUsageReport []map[string]interface{} `json:"secondaryRatUsageReport,omitempty"`

	SecondaryRatUsageInfo []map[string]interface{} `json:"secondaryRatUsageInfo,omitempty"`
}
