/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nfserver

import (
	"fmt"
	"net/http"
	"io"
)

// 訪問根目錄的處理函數，簡單的打印Hello World！
func ApiRoot(w http.ResponseWriter, r *http.Request) {
	io.WriteString(w, r.RequestURI)
	io.WriteString(w, "You are accessing the root path of API, please use right URI to access it!")
}

func DefaultHandler(w http.ResponseWriter,r *http.Request){
	io.WriteString(w,r.RequestURI)
	io.WriteString(w,"This is API Server, please access it using right URI.")
}

// PostSmContexts - Create SM Context 的請求處理函數
func PostSmContexts(w http.ResponseWriter, r *http.Request) {
	fmt.Println("receive message")
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.Write([]byte("I has received your request message."))
	w.WriteHeader(http.StatusOK)
}