/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	"github.com/jerryduren/5gc/nfframe/nfserver"
)

func main() {
	log.Printf("SMF PDU_Sesssion Server started!")

	router := nfserver.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router)) // 用自己的router接管了http包缺省的router
}
