/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nsmfpduserver

// UpCnxState - Possible values are - ACTIVATED - DEACTIVATED - ACTIVATING 
type UpCnxState struct {
}
