/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nsmfpduserver

type SmContextUpdateData struct {

	Pei *map[string]interface{} `json:"pei,omitempty"`

	Gpsi *map[string]interface{} `json:"gpsi,omitempty"`

	ServingNfId *map[string]interface{} `json:"servingNfId,omitempty"`

	Guami *map[string]interface{} `json:"guami,omitempty"`

	ServingNetwork *map[string]interface{} `json:"servingNetwork,omitempty"`

	BackupAmfInfo []map[string]interface{} `json:"backupAmfInfo,omitempty"`

	AnType *map[string]interface{} `json:"anType,omitempty"`

	RatType *map[string]interface{} `json:"ratType,omitempty"`

	PresenceInLadn *map[string]interface{} `json:"presenceInLadn,omitempty"`

	UeLocation *map[string]interface{} `json:"ueLocation,omitempty"`

	UeTimeZone *map[string]interface{} `json:"ueTimeZone,omitempty"`

	AddUeLocation *map[string]interface{} `json:"addUeLocation,omitempty"`

	UpCnxState *UpCnxState `json:"upCnxState,omitempty"`

	HoState *HoState `json:"hoState,omitempty"`

	ToBeSwitched bool `json:"toBeSwitched,omitempty"`

	FailedToBeSwitched bool `json:"failedToBeSwitched,omitempty"`

	N1SmMsg *map[string]interface{} `json:"n1SmMsg,omitempty"`

	N2SmInfo *map[string]interface{} `json:"n2SmInfo,omitempty"`

	N2SmInfoType *N2SmInfoType `json:"n2SmInfoType,omitempty"`

	TargetServingNfId *map[string]interface{} `json:"targetServingNfId,omitempty"`

	SmContextStatusUri *map[string]interface{} `json:"smContextStatusUri,omitempty"`

	DataForwarding bool `json:"dataForwarding,omitempty"`

	EpsBearerSetup []string `json:"epsBearerSetup,omitempty"`

	RevokeEbiList []int32 `json:"revokeEbiList,omitempty"`

	Release bool `json:"release,omitempty"`

	Cause *Cause `json:"cause,omitempty"`

	NgApCause *map[string]interface{} `json:"ngApCause,omitempty"`

	Var5gMmCauseValue *map[string]interface{} `json:"5gMmCauseValue,omitempty"`

	SNssai *map[string]interface{} `json:"sNssai,omitempty"`

	TraceData *map[string]interface{} `json:"traceData,omitempty"`

	EpsInterworkingInd *EpsInterworkingIndication `json:"epsInterworkingInd,omitempty"`

	AnTypeCanBeChanged bool `json:"anTypeCanBeChanged,omitempty"`
}
