/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nsmfpduserver

type QosFlowReleaseRequestItem struct {

	Qfi *map[string]interface{} `json:"qfi"`

	QosRules *map[string]interface{} `json:"qosRules,omitempty"`

	QosFlowDescription *map[string]interface{} `json:"qosFlowDescription,omitempty"`
}
