/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nsmfpduserver

// HoState - Possible values are - NONE - PREPARING - PREPARED - COMPLETED - CANCELLED 
type HoState struct {
}
