/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ts29502nsmfpduserver

type SmContextCreateError struct {

	Error *map[string]interface{} `json:"error"`

	N1SmMsg *map[string]interface{} `json:"n1SmMsg,omitempty"`

	RecoveryTime *map[string]interface{} `json:"recoveryTime,omitempty"`
}
