/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ts29502nsmfpduserver

type PduSessionCreateError struct {

	Error *map[string]interface{} `json:"error"`

	N1smCause string `json:"n1smCause,omitempty"`

	N1SmInfoToUe *map[string]interface{} `json:"n1SmInfoToUe,omitempty"`

	BackOffTimer *map[string]interface{} `json:"backOffTimer,omitempty"`

	RecoveryTime *map[string]interface{} `json:"recoveryTime,omitempty"`
}
