/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ts29502nsmfpduserver

// MaxIntegrityProtectedDataRate - Possible values are   - 64_KBPS   - MAX_UE_RATE 
type MaxIntegrityProtectedDataRate struct {
}
