/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ts29502nsmfpduserver

import (
	"os"
)

type InlineObject struct {

	JsonData *SmContextCreateData `json:"jsonData,omitempty"`

	BinaryDataN1SmMessage **os.File `json:"binaryDataN1SmMessage,omitempty"`
}
