/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ts29502nsmfpduserver

// EpsInterworkingIndication - Possible values are - NONE - WITH_N26 - WITHOUT_N26 
type EpsInterworkingIndication struct {
}
