/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ts29502nsmfpduserver

type QosFlowItem struct {

	Qfi *map[string]interface{} `json:"qfi"`

	Cause *Cause `json:"cause,omitempty"`
}
