/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ts29502nsmfpduserver

type EbiArpMapping struct {

	EpsBearerId int32 `json:"epsBearerId"`

	Arp *map[string]interface{} `json:"arp"`
}
