/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ts29502nsmfpduserver

type TunnelInfo struct {

	Ipv4Addr *map[string]interface{} `json:"ipv4Addr,omitempty"`

	Ipv6Addr *map[string]interface{} `json:"ipv6Addr,omitempty"`

	GtpTeid string `json:"gtpTeid"`
}
