/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ts29502nsmfpduserver

type ReleaseData struct {

	Cause *Cause `json:"cause,omitempty"`

	NgApCause *map[string]interface{} `json:"ngApCause,omitempty"`

	Var5gMmCauseValue *map[string]interface{} `json:"5gMmCauseValue,omitempty"`

	UeLocation *map[string]interface{} `json:"ueLocation,omitempty"`

	UeTimeZone *map[string]interface{} `json:"ueTimeZone,omitempty"`

	AddUeLocation *map[string]interface{} `json:"addUeLocation,omitempty"`

	SecondaryRatUsageReport []map[string]interface{} `json:"secondaryRatUsageReport,omitempty"`
}
