/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient
type AccessTypeRm string

// List of AccessTypeRm
const (
	_3_GPP_ACCESS AccessTypeRm = "3GPP_ACCESS"
	NON_3_GPP_ACCESS AccessTypeRm = "NON_3GPP_ACCESS"
)