/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type RouteInformation struct {
	Ipv4Addr string `json:"ipv4Addr,omitempty"`
	Ipv6Addr string `json:"ipv6Addr,omitempty"`
	PortNumber int32 `json:"portNumber"`
}
