/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient
import (
	"time"
)

type QosFlowUsageReport struct {
	Qfi int32 `json:"qfi"`
	StartTimeStamp time.Time `json:"startTimeStamp"`
	EndTimeStamp time.Time `json:"endTimeStamp"`
	DownlinkVolume int64 `json:"downlinkVolume"`
	UplinkVolume int64 `json:"uplinkVolume"`
}
