/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type ArpRm struct {
	PriorityLevel int32 `json:"priorityLevel"`
	PreemptCap PreemptionCapability `json:"preemptCap"`
	PreemptVuln PreemptionVulnerability `json:"preemptVuln"`
}
