/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type TraceData struct {
	TraceRef string `json:"traceRef"`
	TraceDepth TraceDepth `json:"traceDepth"`
	NeTypeList string `json:"neTypeList"`
	EventList string `json:"eventList"`
	CollectionEntityIpv4Addr string `json:"collectionEntityIpv4Addr,omitempty"`
	CollectionEntityIpv6Addr string `json:"collectionEntityIpv6Addr,omitempty"`
	InterfaceList string `json:"interfaceList,omitempty"`
}
