/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type NrfInfo struct {
	ServedUdrInfo map[string]UdrInfo `json:"servedUdrInfo,omitempty"`
	ServedUdmInfo map[string]UdmInfo `json:"servedUdmInfo,omitempty"`
	ServedAusfInfo map[string]AusfInfo `json:"servedAusfInfo,omitempty"`
	ServedAmfInfo map[string]AmfInfo `json:"servedAmfInfo,omitempty"`
	ServedSmfInfo map[string]SmfInfo `json:"servedSmfInfo,omitempty"`
	ServedUpfInfo map[string]UpfInfo `json:"servedUpfInfo,omitempty"`
	ServedPcfInfo map[string]PcfInfo `json:"servedPcfInfo,omitempty"`
	ServedBsfInfo map[string]BsfInfo `json:"servedBsfInfo,omitempty"`
	ServedChfInfo map[string]ChfInfo `json:"servedChfInfo,omitempty"`
}
