/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type RouteToLocation struct {
	Dnai string `json:"dnai"`
	RouteInfo RouteInformation `json:"routeInfo,omitempty"`
	RouteProfId string `json:"routeProfId,omitempty"`
}
