/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type AmfInfo struct {
	AmfSetId string `json:"amfSetId"`
	AmfRegionId string `json:"amfRegionId"`
	GuamiList []Guami `json:"guamiList"`
	TaiList []Tai `json:"taiList,omitempty"`
	TaiRangeList []TaiRange `json:"taiRangeList,omitempty"`
	BackupInfoAmfFailure []Guami `json:"backupInfoAmfFailure,omitempty"`
	BackupInfoAmfRemoval []Guami `json:"backupInfoAmfRemoval,omitempty"`
	N2InterfaceAmfInfo N2InterfaceAmfInfo `json:"n2InterfaceAmfInfo,omitempty"`
}
