/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type InvalidParam struct {
	Param string `json:"param"`
	Reason string `json:"reason,omitempty"`
}
