/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type InterfaceUpfInfoItem struct {
	InterfaceType UpInterfaceType `json:"interfaceType"`
	Ipv4EndpointAddresses []string `json:"ipv4EndpointAddresses,omitempty"`
	Ipv6EndpointAddresses []string `json:"ipv6EndpointAddresses,omitempty"`
	EndpointFqdn string `json:"endpointFqdn,omitempty"`
	NetworkInstance string `json:"networkInstance,omitempty"`
}
