/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type Atom struct {
	Attr string `json:"attr"`
	Value map[string]interface{} `json:"value"`
	Negative bool `json:"negative,omitempty"`
}
