/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type NonDynamic5Qi struct {
	PriorityLevel int32 `json:"priorityLevel,omitempty"`
	AverWindow int32 `json:"averWindow,omitempty"`
	MaxDataBurstVol int32 `json:"maxDataBurstVol,omitempty"`
}
