/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type PatchItem struct {
	Op PatchOperation `json:"op"`
	Path string `json:"path"`
	From string `json:"from,omitempty"`
	Value map[string]interface{} `json:"value,omitempty"`
}
