/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type N2InterfaceAmfInfo struct {
	Ipv4EndpointAddress []string `json:"ipv4EndpointAddress,omitempty"`
	Ipv6EndpointAddress []string `json:"ipv6EndpointAddress,omitempty"`
	AmfName string `json:"amfName,omitempty"`
}
