/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type SubscribedDefaultQos struct {
	Var5qi int32 `json:"5qi"`
	Arp Arp `json:"arp"`
	PriorityLevel int32 `json:"priorityLevel,omitempty"`
}
