/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type PlmnRange struct {
	Start string `json:"start,omitempty"`
	End string `json:"end,omitempty"`
	Pattern string `json:"pattern,omitempty"`
}
