/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type BackupAmfInfo struct {
	BackupAmf string `json:"backupAmf"`
	GuamiList []Guami `json:"guamiList,omitempty"`
}
