/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type ChfInfo struct {
	SupiRangeList []SupiRange `json:"supiRangeList,omitempty"`
	GpsiRangeList []IdentityRange `json:"gpsiRangeList,omitempty"`
	PlmnRangeList []PlmnRange `json:"plmnRangeList,omitempty"`
}
