/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type NotifCondition struct {
	MonitoredAttributes []string `json:"monitoredAttributes,omitempty"`
	UnmonitoredAttributes []string `json:"unmonitoredAttributes,omitempty"`
}
