/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type OdbData struct {
	RoamingOdb RoamingOdb `json:"roamingOdb,omitempty"`
	OdbPacketServices OdbPacketServices `json:"odbPacketServices,omitempty"`
}
