/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient

type PcfInfo struct {
	DnnList []string `json:"dnnList,omitempty"`
	SupiRanges []SupiRange `json:"supiRanges,omitempty"`
	RxDiamHost string `json:"rxDiamHost,omitempty"`
	RxDiamRealm string `json:"rxDiamRealm,omitempty"`
}
