/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package svcmngclient
import (
	"time"
)

type SubscriptionData struct {
	NfStatusNotificationUri string `json:"nfStatusNotificationUri"`
	SubscrCond map[string]interface{} `json:"subscrCond,omitempty"`
	SubscriptionId string `json:"subscriptionId"`
	ValidityTime time.Time `json:"validityTime,omitempty"`
	ReqNotifEvents []NotificationEventType `json:"reqNotifEvents,omitempty"`
	PlmnId PlmnId `json:"plmnId,omitempty"`
	NotifCondition NotifCondition `json:"notifCondition,omitempty"`
	ReqNfType NfType `json:"reqNfType,omitempty"`
	ReqNfFqdn string `json:"reqNfFqdn,omitempty"`
}
