/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nsmfpduclient

type EpsPdnCnxInfo struct {
	PgwS8cFteid map[string]interface{} `json:"pgwS8cFteid"`
	PgwNodeName map[string]interface{} `json:"pgwNodeName,omitempty"`
}
