/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nsmfpduclient

type StatusInfo struct {
	ResourceStatus ResourceStatus `json:"resourceStatus"`
	Cause Cause `json:"cause,omitempty"`
}
