/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nsmfpduclient

type QosFlowSetupItem struct {
	Qfi map[string]interface{} `json:"qfi"`
	QosRules map[string]interface{} `json:"qosRules"`
	Ebi int32 `json:"ebi,omitempty"`
	QosFlowDescription map[string]interface{} `json:"qosFlowDescription,omitempty"`
	QosFlowProfile QosFlowProfile `json:"qosFlowProfile,omitempty"`
}
