/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nsmfpduclient

type GbrQosFlowInformation struct {
	MaxFbrDl map[string]interface{} `json:"maxFbrDl"`
	MaxFbrUl map[string]interface{} `json:"maxFbrUl"`
	GuaFbrDl map[string]interface{} `json:"guaFbrDl"`
	GuaFbrUl map[string]interface{} `json:"guaFbrUl"`
	NotifControl map[string]interface{} `json:"notifControl,omitempty"`
	MaxPacketLossRateDl map[string]interface{} `json:"maxPacketLossRateDl,omitempty"`
	MaxPacketLossRateUl map[string]interface{} `json:"maxPacketLossRateUl,omitempty"`
}
