/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nsmfpduclient

type HsmfUpdateError struct {
	Error map[string]interface{} `json:"error"`
	Pti int32 `json:"pti,omitempty"`
	N1smCause string `json:"n1smCause,omitempty"`
	N1SmInfoToUe map[string]interface{} `json:"n1SmInfoToUe,omitempty"`
	BackOffTimer map[string]interface{} `json:"backOffTimer,omitempty"`
	RecoveryTime map[string]interface{} `json:"recoveryTime,omitempty"`
}
