/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29502nsmfpduclient

type ProblemDetails struct {
	Type string `json:"type,omitempty"`
	Title string `json:"title,omitempty"`
	Status int32 `json:"status,omitempty"`
	Detail string `json:"detail,omitempty"`
	Instance string `json:"instance,omitempty"`
	Cause string `json:"cause,omitempty"`
	InvalidParams []InvalidParam `json:"invalidParams,omitempty"`
}
