/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29502nsmfpduclient

type TunnelInfo struct {
	Ipv4Addr map[string]interface{} `json:"ipv4Addr,omitempty"`
	Ipv6Addr map[string]interface{} `json:"ipv6Addr,omitempty"`
	GtpTeid string `json:"gtpTeid"`
}
