/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29502nsmfpduclient

type SmContextUpdatedData struct {
	UpCnxState UpCnxState `json:"upCnxState,omitempty"`
	HoState HoState `json:"hoState,omitempty"`
	ReleaseEbiList []int32 `json:"releaseEbiList,omitempty"`
	AllocatedEbiList []EbiArpMapping `json:"allocatedEbiList,omitempty"`
	ModifiedEbiList []EbiArpMapping `json:"modifiedEbiList,omitempty"`
	N1SmMsg map[string]interface{} `json:"n1SmMsg,omitempty"`
	N2SmInfo map[string]interface{} `json:"n2SmInfo,omitempty"`
	N2SmInfoType N2SmInfoType `json:"n2SmInfoType,omitempty"`
	EpsBearerSetup []string `json:"epsBearerSetup,omitempty"`
	DataForwarding bool `json:"dataForwarding,omitempty"`
}
