/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29502nsmfpduclient

type VsmfUpdateData struct {
	RequestIndication RequestIndication `json:"requestIndication"`
	SessionAmbr map[string]interface{} `json:"sessionAmbr,omitempty"`
	QosFlowsAddModRequestList []QosFlowAddModifyRequestItem `json:"qosFlowsAddModRequestList,omitempty"`
	QosFlowsRelRequestList []QosFlowReleaseRequestItem `json:"qosFlowsRelRequestList,omitempty"`
	EpsBearerInfo []EpsBearerInfo `json:"epsBearerInfo,omitempty"`
	AssignEbiList []int32 `json:"assignEbiList,omitempty"`
	RevokeEbiList []int32 `json:"revokeEbiList,omitempty"`
	ModifiedEbiList []EbiArpMapping `json:"modifiedEbiList,omitempty"`
	Pti int32 `json:"pti,omitempty"`
	N1SmInfoToUe map[string]interface{} `json:"n1SmInfoToUe,omitempty"`
	AlwaysOnGranted bool `json:"alwaysOnGranted,omitempty"`
	Cause Cause `json:"cause,omitempty"`
	N1smCause string `json:"n1smCause,omitempty"`
	BackOffTimer map[string]interface{} `json:"backOffTimer,omitempty"`
}
