/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29502nsmfpduclient

type SmContextCreatedData struct {
	HSmfUri map[string]interface{} `json:"hSmfUri,omitempty"`
	PduSessionId map[string]interface{} `json:"pduSessionId,omitempty"`
	SNssai map[string]interface{} `json:"sNssai,omitempty"`
	UpCnxState UpCnxState `json:"upCnxState,omitempty"`
	N2SmInfo map[string]interface{} `json:"n2SmInfo,omitempty"`
	N2SmInfoType N2SmInfoType `json:"n2SmInfoType,omitempty"`
	AllocatedEbiList []EbiArpMapping `json:"allocatedEbiList,omitempty"`
	HoState HoState `json:"hoState,omitempty"`
	SmfServiceInstanceId string `json:"smfServiceInstanceId,omitempty"`
	RecoveryTime map[string]interface{} `json:"recoveryTime,omitempty"`
	SupportedFeatures map[string]interface{} `json:"supportedFeatures,omitempty"`
}
