/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29502nsmfpduclient

type EpsBearerInfo struct {
	Ebi int32 `json:"ebi"`
	PgwS8uFteid map[string]interface{} `json:"pgwS8uFteid"`
	BearerLevelQoS map[string]interface{} `json:"bearerLevelQoS"`
}
