/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29502nsmfpduclient

type SmContextCreateData struct {
	Supi map[string]interface{} `json:"supi,omitempty"`
	UnauthenticatedSupi bool `json:"unauthenticatedSupi,omitempty"`
	Pei map[string]interface{} `json:"pei,omitempty"`
	Gpsi map[string]interface{} `json:"gpsi,omitempty"`
	PduSessionId map[string]interface{} `json:"pduSessionId,omitempty"`
	Dnn map[string]interface{} `json:"dnn,omitempty"`
	SNssai map[string]interface{} `json:"sNssai,omitempty"`
	HplmnSnssai map[string]interface{} `json:"hplmnSnssai,omitempty"`
	ServingNfId map[string]interface{} `json:"servingNfId"`
	Guami map[string]interface{} `json:"guami,omitempty"`
	ServiceName map[string]interface{} `json:"serviceName,omitempty"`
	ServingNetwork map[string]interface{} `json:"servingNetwork"`
	RequestType RequestType `json:"requestType,omitempty"`
	N1SmMsg map[string]interface{} `json:"n1SmMsg,omitempty"`
	AnType map[string]interface{} `json:"anType"`
	RatType map[string]interface{} `json:"ratType,omitempty"`
	PresenceInLadn map[string]interface{} `json:"presenceInLadn,omitempty"`
	UeLocation map[string]interface{} `json:"ueLocation,omitempty"`
	UeTimeZone map[string]interface{} `json:"ueTimeZone,omitempty"`
	AddUeLocation map[string]interface{} `json:"addUeLocation,omitempty"`
	SmContextStatusUri map[string]interface{} `json:"smContextStatusUri"`
	HSmfUri map[string]interface{} `json:"hSmfUri,omitempty"`
	AdditionalHsmfUri []map[string]interface{} `json:"additionalHsmfUri,omitempty"`
	OldPduSessionId map[string]interface{} `json:"oldPduSessionId,omitempty"`
	PduSessionsActivateList []map[string]interface{} `json:"pduSessionsActivateList,omitempty"`
	UeEpsPdnConnection string `json:"ueEpsPdnConnection,omitempty"`
	HoState HoState `json:"hoState,omitempty"`
	PcfId map[string]interface{} `json:"pcfId,omitempty"`
	NrfUri map[string]interface{} `json:"nrfUri,omitempty"`
	SupportedFeatures map[string]interface{} `json:"supportedFeatures,omitempty"`
	SelMode DnnSelectionMode `json:"selMode,omitempty"`
	BackupAmfInfo []map[string]interface{} `json:"backupAmfInfo,omitempty"`
	TraceData map[string]interface{} `json:"traceData,omitempty"`
	UdmGroupId map[string]interface{} `json:"udmGroupId,omitempty"`
	RoutingIndicator string `json:"routingIndicator,omitempty"`
	EpsInterworkingInd EpsInterworkingIndication `json:"epsInterworkingInd,omitempty"`
	IndirectForwardingFlag bool `json:"indirectForwardingFlag,omitempty"`
}
