/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29502nsmfpduclient

type SmContextCreateError struct {
	Error map[string]interface{} `json:"error"`
	N1SmMsg map[string]interface{} `json:"n1SmMsg,omitempty"`
	RecoveryTime map[string]interface{} `json:"recoveryTime,omitempty"`
}
