/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ts29502nsmfpduclient

type EbiArpMapping struct {
	EpsBearerId int32 `json:"epsBearerId"`
	Arp map[string]interface{} `json:"arp"`
}
