/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smfserver

type EpsPdnCnxInfo struct {

	PgwS8cFteid string `json:"pgwS8cFteid"`

	PgwNodeName string `json:"pgwNodeName,omitempty"`
}
