/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smfserver

type Tai struct {

	PlmnId *PlmnId `json:"plmnId"`

	Tac string `json:"tac"`
}
