/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

type SmContextUpdateData struct {
	Pei map[string]interface{} `json:"pei,omitempty"`
	ServingNfId map[string]interface{} `json:"servingNfId,omitempty"`
	Guami map[string]interface{} `json:"guami,omitempty"`
	ServingNetwork map[string]interface{} `json:"servingNetwork,omitempty"`
	BackupAmfInfo []map[string]interface{} `json:"backupAmfInfo,omitempty"`
	AnType map[string]interface{} `json:"anType,omitempty"`
	SecondAnType map[string]interface{} `json:"secondAnType,omitempty"`
	RatType map[string]interface{} `json:"ratType,omitempty"`
	PresenceInLadn map[string]interface{} `json:"presenceInLadn,omitempty"`
	UeLocation map[string]interface{} `json:"ueLocation,omitempty"`
	UeTimeZone map[string]interface{} `json:"ueTimeZone,omitempty"`
	AddUeLocation map[string]interface{} `json:"addUeLocation,omitempty"`
	UpCnxState UpCnxState `json:"upCnxState,omitempty"`
	HoState HoState `json:"hoState,omitempty"`
	ToBeSwitched bool `json:"toBeSwitched,omitempty"`
	FailedToBeSwitched bool `json:"failedToBeSwitched,omitempty"`
	N1SmMsg map[string]interface{} `json:"n1SmMsg,omitempty"`
	N2SmInfo map[string]interface{} `json:"n2SmInfo,omitempty"`
	N2SmInfoType N2SmInfoType `json:"n2SmInfoType,omitempty"`
	TargetId map[string]interface{} `json:"targetId,omitempty"`
	TargetServingNfId map[string]interface{} `json:"targetServingNfId,omitempty"`
	SmContextStatusUri map[string]interface{} `json:"smContextStatusUri,omitempty"`
	DataForwarding bool `json:"dataForwarding,omitempty"`
	EpsBearerSetup []string `json:"epsBearerSetup,omitempty"`
	RevokeEbiList []int32 `json:"revokeEbiList,omitempty"`
	Release bool `json:"release,omitempty"`
	Cause Cause `json:"cause,omitempty"`
	NgApCause map[string]interface{} `json:"ngApCause,omitempty"`
	Var5gMmCauseValue map[string]interface{} `json:"5gMmCauseValue,omitempty"`
	SNssai map[string]interface{} `json:"sNssai,omitempty"`
	TraceData map[string]interface{} `json:"traceData,omitempty"`
	EpsInterworkingInd EpsInterworkingIndication `json:"epsInterworkingInd,omitempty"`
	AnTypeCanBeChanged bool `json:"anTypeCanBeChanged,omitempty"`
	N2SmInfoExt1 map[string]interface{} `json:"n2SmInfoExt1,omitempty"`
	N2SmInfoTypeExt1 N2SmInfoType `json:"n2SmInfoTypeExt1,omitempty"`
	MaReleaseInd MaReleaseIndication `json:"maReleaseInd,omitempty"`
	ExemptionInd ExemptionInd `json:"exemptionInd,omitempty"`
}
