/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

type SmContextCreatedData struct {
	HSmfUri map[string]interface{} `json:"hSmfUri,omitempty"`
	PduSessionId map[string]interface{} `json:"pduSessionId,omitempty"`
	SNssai map[string]interface{} `json:"sNssai,omitempty"`
	UpCnxState UpCnxState `json:"upCnxState,omitempty"`
	N2SmInfo map[string]interface{} `json:"n2SmInfo,omitempty"`
	N2SmInfoType N2SmInfoType `json:"n2SmInfoType,omitempty"`
	AllocatedEbiList []EbiArpMapping `json:"allocatedEbiList,omitempty"`
	HoState HoState `json:"hoState,omitempty"`
	Gpsi map[string]interface{} `json:"gpsi,omitempty"`
	SmfServiceInstanceId string `json:"smfServiceInstanceId,omitempty"`
	RecoveryTime map[string]interface{} `json:"recoveryTime,omitempty"`
	SupportedFeatures map[string]interface{} `json:"supportedFeatures,omitempty"`
}
