/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

type SmContextReleaseData struct {
	Cause Cause `json:"cause,omitempty"`
	NgApCause map[string]interface{} `json:"ngApCause,omitempty"`
	Var5gMmCauseValue map[string]interface{} `json:"5gMmCauseValue,omitempty"`
	UeLocation map[string]interface{} `json:"ueLocation,omitempty"`
	UeTimeZone map[string]interface{} `json:"ueTimeZone,omitempty"`
	AddUeLocation map[string]interface{} `json:"addUeLocation,omitempty"`
	VsmfReleaseOnly bool `json:"vsmfReleaseOnly,omitempty"`
	N2SmInfo map[string]interface{} `json:"n2SmInfo,omitempty"`
	N2SmInfoType N2SmInfoType `json:"n2SmInfoType,omitempty"`
	IsmfReleaseOnly bool `json:"ismfReleaseOnly,omitempty"`
}
