/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

type VsmfUpdateError struct {
	Error map[string]interface{} `json:"error"`
	Pti int32 `json:"pti,omitempty"`
	N1smCause string `json:"n1smCause,omitempty"`
	N1SmInfoFromUe map[string]interface{} `json:"n1SmInfoFromUe,omitempty"`
	UnknownN1SmInfo map[string]interface{} `json:"unknownN1SmInfo,omitempty"`
	FailedToAssignEbiList []int32 `json:"failedToAssignEbiList,omitempty"`
	NgApCause map[string]interface{} `json:"ngApCause,omitempty"`
	Var5gMmCauseValue map[string]interface{} `json:"5gMmCauseValue,omitempty"`
	RecoveryTime map[string]interface{} `json:"recoveryTime,omitempty"`
}
