/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

type PduSessionCreateError struct {
	Error map[string]interface{} `json:"error"`
	N1smCause string `json:"n1smCause,omitempty"`
	N1SmInfoToUe map[string]interface{} `json:"n1SmInfoToUe,omitempty"`
	BackOffTimer map[string]interface{} `json:"backOffTimer,omitempty"`
	RecoveryTime map[string]interface{} `json:"recoveryTime,omitempty"`
}
