/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

type VsmfUpdateData struct {
	RequestIndication RequestIndication `json:"requestIndication"`
	SessionAmbr map[string]interface{} `json:"sessionAmbr,omitempty"`
	QosFlowsAddModRequestList []QosFlowAddModifyRequestItem `json:"qosFlowsAddModRequestList,omitempty"`
	QosFlowsRelRequestList []QosFlowReleaseRequestItem `json:"qosFlowsRelRequestList,omitempty"`
	EpsBearerInfo []EpsBearerInfo `json:"epsBearerInfo,omitempty"`
	AssignEbiList []int32 `json:"assignEbiList,omitempty"`
	RevokeEbiList []int32 `json:"revokeEbiList,omitempty"`
	ModifiedEbiList []EbiArpMapping `json:"modifiedEbiList,omitempty"`
	Pti int32 `json:"pti,omitempty"`
	N1SmInfoToUe map[string]interface{} `json:"n1SmInfoToUe,omitempty"`
	AlwaysOnGranted bool `json:"alwaysOnGranted,omitempty"`
	HsmfPduSessionUri map[string]interface{} `json:"hsmfPduSessionUri,omitempty"`
	SupportedFeatures map[string]interface{} `json:"supportedFeatures,omitempty"`
	Cause Cause `json:"cause,omitempty"`
	N1smCause string `json:"n1smCause,omitempty"`
	BackOffTimer map[string]interface{} `json:"backOffTimer,omitempty"`
	MaReleaseInd MaReleaseIndication `json:"maReleaseInd,omitempty"`
}
