/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

type PduSessionCreatedData struct {
	PduSessionType map[string]interface{} `json:"pduSessionType"`
	SscMode string `json:"sscMode"`
	HcnTunnelInfo TunnelInfo `json:"hcnTunnelInfo,omitempty"`
	SessionAmbr map[string]interface{} `json:"sessionAmbr,omitempty"`
	QosFlowsSetupList []QosFlowSetupItem `json:"qosFlowsSetupList,omitempty"`
	HSmfInstanceId map[string]interface{} `json:"hSmfInstanceId"`
	PduSessionId map[string]interface{} `json:"pduSessionId,omitempty"`
	SNssai map[string]interface{} `json:"sNssai,omitempty"`
	EnablePauseCharging bool `json:"enablePauseCharging,omitempty"`
	UeIpv4Address map[string]interface{} `json:"ueIpv4Address,omitempty"`
	UeIpv6Prefix map[string]interface{} `json:"ueIpv6Prefix,omitempty"`
	N1SmInfoToUe map[string]interface{} `json:"n1SmInfoToUe,omitempty"`
	EpsPdnCnxInfo EpsPdnCnxInfo `json:"epsPdnCnxInfo,omitempty"`
	EpsBearerInfo []EpsBearerInfo `json:"epsBearerInfo,omitempty"`
	SupportedFeatures map[string]interface{} `json:"supportedFeatures,omitempty"`
	MaxIntegrityProtectedDataRate MaxIntegrityProtectedDataRate `json:"maxIntegrityProtectedDataRate,omitempty"`
	AlwaysOnGranted bool `json:"alwaysOnGranted,omitempty"`
	Gpsi map[string]interface{} `json:"gpsi,omitempty"`
	UpSecurity map[string]interface{} `json:"upSecurity,omitempty"`
	RoamingChargingProfile map[string]interface{} `json:"roamingChargingProfile,omitempty"`
	HSmfServiceInstanceId string `json:"hSmfServiceInstanceId,omitempty"`
	RecoveryTime map[string]interface{} `json:"recoveryTime,omitempty"`
}
