/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

type SmContextUpdateError struct {
	Error map[string]interface{} `json:"error"`
	N1SmMsg map[string]interface{} `json:"n1SmMsg,omitempty"`
	N2SmInfo map[string]interface{} `json:"n2SmInfo,omitempty"`
	N2SmInfoType N2SmInfoType `json:"n2SmInfoType,omitempty"`
	UpCnxState UpCnxState `json:"upCnxState,omitempty"`
	RecoveryTime map[string]interface{} `json:"recoveryTime,omitempty"`
}
