/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

type SmContextUpdatedData struct {
	UpCnxState UpCnxState `json:"upCnxState,omitempty"`
	HoState HoState `json:"hoState,omitempty"`
	ReleaseEbiList []int32 `json:"releaseEbiList,omitempty"`
	AllocatedEbiList []EbiArpMapping `json:"allocatedEbiList,omitempty"`
	ModifiedEbiList []EbiArpMapping `json:"modifiedEbiList,omitempty"`
	N1SmMsg map[string]interface{} `json:"n1SmMsg,omitempty"`
	N2SmInfo map[string]interface{} `json:"n2SmInfo,omitempty"`
	N2SmInfoType N2SmInfoType `json:"n2SmInfoType,omitempty"`
	EpsBearerSetup []string `json:"epsBearerSetup,omitempty"`
	DataForwarding bool `json:"dataForwarding,omitempty"`
	Cause Cause `json:"cause,omitempty"`
}
