/*
 * Common Data Types
 *
 * Common Data Types
 *
 * API version: 1.R15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package TS29571_CommonData

type UpSecurity struct {
	UpIntegr UpIntegrity `json:"upIntegr" xml:"upIntegr"`
	UpConfid UpConfidentiality `json:"upConfid" xml:"upConfid"`
}
