/*
 * Common Data Types
 *
 * Common Data Types
 *
 * API version: 1.R15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package TS29571_CommonData

type Ncgi struct {
	PlmnId PlmnId `json:"plmnId" xml:"plmnId"`
	NrCellId string `json:"nrCellId" xml:"nrCellId"`
}
