/*
 * Common Data Types
 *
 * Common Data Types
 *
 * API version: 1.R15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package TS29571_CommonData

type PatchItem struct {
	Op PatchOperation `json:"op" xml:"op"`
	Path string `json:"path" xml:"path"`
	From string `json:"from,omitempty" xml:"from"`
	Value map[string]interface{} `json:"value,omitempty" xml:"value"`
}
