/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0.alpha-1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package commondata

type NfDiscFactors struct {

	TargetNfType *NfType `json:"targetNfType,omitempty"`

	RequesterNfType *NfType `json:"requesterNfType,omitempty"`

	ServiceNames []ServiceName `json:"serviceNames,omitempty"`

	RequesterNfInstanceFqdn string `json:"requesterNfInstanceFqdn,omitempty"`

	TargetPlmnList []PlmnId `json:"targetPlmnList,omitempty"`

	RequesterPlmnList []PlmnId `json:"requesterPlmnList,omitempty"`

	TargetNfInstanceId string `json:"targetNfInstanceId,omitempty"`

	TargetNfFqdn string `json:"targetNfFqdn,omitempty"`

	HnrfUri string `json:"hnrfUri,omitempty"`

	Snssais []Snssai `json:"snssais,omitempty"`

	PlmnSpecificSnssaiList []PlmnSnssai `json:"plmnSpecificSnssaiList,omitempty"`

	Dnn string `json:"dnn,omitempty"`

	NsiList []string `json:"nsiList,omitempty"`

	Tai *Tai `json:"tai,omitempty"`

	AmfRegionId string `json:"amfRegionId,omitempty"`

	AmfSetId string `json:"amfSetId,omitempty"`

	Guami *Guami `json:"guami,omitempty"`

	Supi string `json:"supi,omitempty"`

	UeIpv4Address string `json:"ueIpv4Address,omitempty"`

	IpDomain string `json:"ipDomain,omitempty"`

	UeIpv6Prefix string `json:"ueIpv6Prefix,omitempty"`

	PgwInd bool `json:"pgwInd,omitempty"`

	Pgw string `json:"pgw,omitempty"`

	Gpsi string `json:"gpsi,omitempty"`

	ExternalGroupIdentity string `json:"externalGroupIdentity,omitempty"`

	DataSet *DataSetId `json:"dataSet,omitempty"`

	RoutingIndicator string `json:"routingIndicator,omitempty"`

	GroupIdList []string `json:"groupIdList,omitempty"`

	DnaiList []string `json:"dnaiList,omitempty"`

	PduSessionTypes []PduSessionType `json:"pduSessionTypes,omitempty"`

	UpfIwkEpsInd bool `json:"upfIwkEpsInd,omitempty"`

	ChfSupportedPlmn *PlmnId `json:"chfSupportedPlmn,omitempty"`

	PreferredLocality string `json:"preferredLocality,omitempty"`

	AccessType *AccessType `json:"accessType,omitempty"`

	RequiredFeatures []string `json:"requiredFeatures,omitempty"`

	ComplexQuery *ComplexQuery `json:"complexQuery,omitempty"`
}
