/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0.alpha-1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package commondata

type NonDynamic5Qi struct {

	PriorityLevel int32 `json:"priorityLevel,omitempty"`

	AverWindow int32 `json:"averWindow,omitempty"`

	MaxDataBurstVol int32 `json:"maxDataBurstVol,omitempty"`
}
