/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0.alpha-1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package commondata

type AccessTypeRm string

// List of AccessTypeRm
const (
	_3_GPP_ACCESS_RM AccessTypeRm = "3GPP_ACCESS"
	NON_3_GPP_ACCESS_RM AccessTypeRm = "NON_3GPP_ACCESS"
)
