/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0.alpha-1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package commondata

type PatchItem struct {

	Op *PatchOperation `json:"op"`

	Path string `json:"path"`

	From string `json:"from,omitempty"`

	Value *map[string]interface{} `json:"value,omitempty"`
}
