/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0.alpha-1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package commondata

import (
	"time"
)

type VolumeTimedReport struct {

	StartTimeStamp time.Time `json:"startTimeStamp"`

	EndTimeStamp time.Time `json:"endTimeStamp"`

	DownlinkVolume int64 `json:"downlinkVolume"`

	UplinkVolume int64 `json:"uplinkVolume"`
}
