/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0.alpha-1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package commondata

type PresenceInfo struct {

	PraId string `json:"praId,omitempty"`

	PresenceState *PresenceState `json:"presenceState,omitempty"`

	TrackingAreaList []Tai `json:"trackingAreaList,omitempty"`

	EcgiList []Ecgi `json:"ecgiList,omitempty"`

	NcgiList []Ncgi `json:"ncgiList,omitempty"`

	GlobalRanNodeIdList []GlobalRanNodeId `json:"globalRanNodeIdList,omitempty"`
}
